//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGrade
    {
        public int StudentID { get; set; }
        public string GradeID { get; set; }
        public int LessonID { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
